type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
  userType: String # Replaces enum for now
}

type Station @table {
  owner: User
  name: String!
  address: String!
  latitude: Float!
  longitude: Float!
  createdAt: Timestamp!
  phoneNumber: String
  website: String
  hoursOfOperation: String
  amenities: [String]
}

type FuelPrice @table {
  station: Station!
  updater: User!
  fuelType: String! # Replaces enum for now
  price: Float!
  updatedAt: Timestamp!
  isEstimated: Boolean
}

type Review @table {
  station: Station!
  reviewer: User!
  rating: Int!
  createdAt: Timestamp!
  comment: String
  updatedAt: Timestamp
}

type FavoriteStation @table(key: ["user", "station"]) {
  user: User!
  station: Station!
  createdAt: Timestamp!
}